/**
 * A hashmap to assist in making output from pa11y reports human-readable
 */
module.exports = {
    "principle": {
        "Principle1": "Perceivable",
        "Principle2": "Operable",
        "Principle3": "Understandable",
        "Principle4": "Robust"
    },
    "guideline": {
        "Guideline1_1": "Text Alternatives",
        "Guideline1_2": "Time-based Media",
        "Guideline1_3": "Adaptable",
        "Guideline1_4": "Distinguishable",
        "Guideline2_1": "Keyboard Accessible",
        "Guideline2_2": "Enough Time",
        "Guideline2_3": "Seizures",
        "Guideline2_4": "Navigable",
        "Guideline3_1": "Readable",
        "Guideline3_2": "Predictable",
        "Guideline3_3": "Input Assistance",
        "Guideline4_1": "Compatible"
    },
    "rule": {
        "1_1_1": "Non-text Content",
        "1_2_1": "Audio-only and Video-only (Prerecorded)",
        "1_2_2": "Captions (Prerecorded)",
        "1_2_3": "Audio Description or Media Alternative (Prerecorded)",
        "1_2_4": "Captions (Live)",
        "1_2_5": "Audio Description (Prerecorded)",
        "1_2_6": "Sign Language (Prerecorded)",
        "1_2_7": "Extended Audio Description (Prerecorded)",
        "1_2_8": "Media Alternative (Prerecorded)",
        "1_2_9": "Audio-only (Live)",
        "1_3_1": "Info and Relationships",
        "1_3_2": "Meaningful Sequence",
        "1_3_3": "Sensory Characteristics",
        "1_4_1": "Use of Color",
        "1_4_2": "Audio Control",
        "1_4_3": "Contrast (Minimum)",
        "1_4_4": "Resize text",
        "1_4_5": "Images of Text",
        "1_4_6": "Contrast (Enhanced)",
        "1_4_7": "Low or No Background Audio",
        "1_4_8": "Visual Presentation",
        "1_4_9": "Images of Text (No Exception)",
        "2_1_1": "Keyboard",
        "2_1_2": "No Keyboard Trap",
        "2_1_3": "Keyboard (No Exception)",
        "2_2_1": "Timing Adjustable",
        "2_2_2": "Pause, Stop, Hide",
        "2_2_3": "No Timing",
        "2_2_4": "Interruptions",
        "2_2_5": "Re-authenticating",
        "2_3_1": "Three Flashes or Below Threshold",
        "2_3_2": "Three Flashes",
        "2_4_1": "Bypass Blocks",
        "2_4_2": "Page Titled",
        "2_4_3": "Focus Order",
        "2_4_4": "Link Purpose (In Context)",
        "2_4_5": "Multiple Ways",
        "2_4_6": "Headings and Labels",
        "2_4_7": "Focus Visible",
        "2_4_8": "Location",
        "2_4_9": "Link Purpose (Link Only)",
        "2_4_10": "Section Headings",
        "3_1_1": "Language of Page",
        "3_1_2": "Language of Parts",
        "3_1_3": "Unusual Words",
        "3_1_4": "Abbreviations",
        "3_1_5": "Reading Level",
        "3_1_6": "Pronunciation",
        "3_2_1": "On Focus",
        "3_2_2": "On Input",
        "3_2_3": "Consistent Navigation",
        "3_2_4": "Consistent Identification",
        "3_2_5": "Change on Request",
        "3_3_1": "Error Identification",
        "3_3_2": "Labels or Instructions",
        "3_3_3": "Error Suggestion",
        "3_3_4": "Error Prevention (Legal, Financial, Data)",
        "3_3_5": "Help",
        "3_3_6": "Error Prevention (All)",
        "4_1_1": "Parsing",
        "4_1_2": "Name, Role, Value"
    }
}